### ISSUE TITLE
OTP can't be sent

### ISSUE THREAD

**Issue by AljawharaTalal** [rohit-chouhan/email_otp#10]
at first the I was receiving the OTP, but today suddenly it started failing. whenever I try to initiate a connection to send the OTP I receive the following error.
E/flutter ( 8341): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
E/flutter ( 8341): 	CERTIFICATE_VERIFY_FAILED: Hostname mismatch(handshake.cc:393))

**Comment by senenpalanca** [comment]
same problem here!

**Comment by fatmaalzhraaesmail** [comment]
same problem here!

**Comment by rohit-chouhan** [comment]
Fixed!!
