### ISSUE TITLE
I can't verify my OTP code that was send to email

### ISSUE THREAD

**Issue by JAngelus21** [rohit-chouhan/email_otp#12]
I have a problem when verifying the OTP code. so I succeed to send the OTP code, but when I try to verify it the result is always false. even though the code that I'm using is same as the "readme" file, the OTP code always can't verify. can anyone help me?

here's how I send the OTP code
Align(
                      alignment: Alignment.center,
                      child: TextButton(
                        onPressed: () async {
                          myauth.setConfig(
                            appEmail: "abcdef@gmail.com",
                            appName: "Email OTP",
                            userEmail: email,
                            otpLength: 6,
                            otpType: OTPType.digitsOnly,
                          );
                          print(
                              'myauth register: ${myauth.verifyOTP(otp: otp)}');
                          if (await myauth.sendOTP() == true) {
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(
                                content: Text("OTP has been sent"),
                              ),
                            );
                          } else {
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(
                                content: Text("Oops, OTP send failed"),
                              ),
                            );
                          }
                        },
                        child: const Text('Send OTP Code'),
                      ),
                    ),
                    
here's how I verify the OTP code
suffixIcon: ElevatedButton(
            style: ElevatedButton.styleFrom(
              shape: const RoundedRectangleBorder(
                borderRadius: BorderRadius.only(
                  topRight: Radius.circular(10),
                  bottomRight: Radius.circular(10),
                ),
              ),
              backgroundColor: Colors.black,
            ),
            onPressed: () async {
              isVerified = await myauth.verifyOTP(otp: inputOtp);
              print('VerifyOTP Result: $isVerified');
              if (isVerified == true) {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text("OTP is verified"),
                  ),
                );
              } else {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text("Invalid OTP"),
                  ),
                );
              }
            },
            child:
                const Icon(Icons.check_circle, size: 20, color: Colors.white),
          ),
        ),

**Comment by rohit-chouhan** [comment]
Apologies for the inconvenience. The issue has been resolved. Please don't hesitate to report any further issues, and thank you for your understanding
