### ISSUE TITLE
Sending OTP failed

### ISSUE THREAD

**Issue by miraa2001** [rohit-chouhan/email_otp#16]
lately the OTP sending returns a false value when this is executed myAuth.sendOTP and i can't seem to find what's the issue

**Comment by miraa2001** [comment]
@rohit-chouhan can you please help me?

**Comment by achego** [comment]
Im having the same issues here, my 
code is breaking

**Comment by rohit-chouhan** [comment]
Apologies for the inconvenience. The issue has been resolved. Please don't hesitate to report any further issues, and thank you for your understanding

**Comment by muditgarg48** [comment]
Its still not working!

**Comment by rohit-chouhan** [comment]
Version 3 released
