### ISSUE TITLE
SMTP Issue  + email configuration is sent as a clear text to your api !!!!!!!!!!!!

### ISSUE THREAD

**Issue by HarGarX** [rohit-chouhan/email_otp#17]
cant send an OTP with custom smtp configs, as the title suggest this issue and the email configuration been sent to an API is very shady in my opinion, if you please clarify

**Comment by ruchirakhankari** [comment]
Facing same issue, have you got solution for this how to configure custom SMTP ?

**Comment by rohit-chouhan** [comment]
If possible can you send me your smtp configs. Make your you are giving
correct port and tls/ssl

**Comment by ruchirakhankari** [comment]
[image: 95C92DDE-0880-4CD0-832F-F5E8AAA4A9DC.jpeg]

Hi Rohit, PFA screenshot of server details and successfully sending OTP
when I checked online
But while running app in flutter its not working.
Your promt response would greatly appreciated.
Thanks,
Ruchira

**Comment by rohit-chouhan** [comment]
thanks for report, we are checking on this. will let you know when its fixed.

**Comment by rohit-chouhan** [comment]
Version 3 released, issue fixed. Please feel free to reopen if you get any issue.

**Comment by ruchirakhankari** [comment]
Great! Thanks for update
