### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by ankitsharma098** [rohit-chouhan/email_otp#19]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ClientException with SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = email-otp.api.rohitchouhan.com, port = 51578, uri=https://email-otp.api.rohitchouhan.com/v2/

**Comment by rohit-chouhan** [comment]
Issue fixed
