### ISSUE TITLE
Cannot verify otp

### ISSUE THREAD

**Issue by achego** [rohit-chouhan/email_otp#2]
Really nice work you've done here, but I'll advice you minimize the use of dynamics, and also try to handle errors then return readable and understandable error message.. I've been trying to verify otp, and I don't know whether the otp field requires a String or a double or hint, because the field is dynamic, and I don't get any error message that can help me out

**Comment by TomasWard1** [comment]
Same here, verify is not working,

**Comment by rohit-chouhan** [comment]
fixed

**Comment by fatmaalzhraaesmail** [comment]
sending otp is work but cannot verify sent otp
