### ISSUE TITLE
OTP validation fails, even if OTP entered is the same.

### ISSUE THREAD

**Issue by soundari2020** [rohit-chouhan/email_otp#23]
getOTP returning a different number. Can you pls check

**Comment by soundari2020** [comment]
Not an issue. Probably looks like the way I implemented is creating the issue.

**Comment by rohit-chouhan** [comment]
To validate the code, please use the verifyOTP() method. The getOTP variable is only for debugging purposes.
Thank you

**Comment by soundari2020** [comment]
Got it. Thank you.
