### ISSUE TITLE
Sent OPT Email is not correct

### ISSUE THREAD

**Issue by sailinhtut** [rohit-chouhan/email_otp#3]
![attach](https://user-images.githubusercontent.com/95534635/213630986-d5fe7539-c897-4026-aaa5-c76bb93723ec.jpg)

That is how I get back when verify. If I click that button , it redirect to a website. I change every release versions all round but doesn't work. It works in sometimes correctly. Please help me . Thank for a good package.

**Comment by rohit-chouhan** [comment]
we have fixed the issue
