### ISSUE TITLE
Showing otp sent but otp is not sent

### ISSUE THREAD

**Issue by Muneeb-Ahmed2002** [rohit-chouhan/email_otp#5]
I used this package to send otp to my application but the problem is I am not able to get the OTP via mail while it says OTP has been sent

**Comment by SilviaCebrian** [comment]
It seems that the web site is not working, I am waiting for it too.

**Comment by Muneeb-Ahmed2002** [comment]
I am working with Email.js

**Comment by SilviaCebrian** [comment]
It works again

**Comment by rohit-chouhan** [comment]
Fixed!
