### ISSUE TITLE
Cant verify otp

### ISSUE THREAD

**Issue by achego** [rohit-chouhan/email_otp#7]
after ive sent the send the otp to email, this part works but the verify part does not work always shows invalid otp

**Comment by nuazal** [comment]
i have the same problem too, please help:'((

**Comment by nuazal** [comment]
> i have the same problem too, please help:'((

today i try it again for my project and the verify part seems to already work

**Comment by Kamal3113** [comment]
otp send successfully but show invalid otp every time .

**Comment by yazidihsan** [comment]
Handshake error in client

**Comment by mohitclover** [comment]
**Unhandled Exception: HandshakeException: Handshake error in client** (OS Error: 
CERTIFICATE_VERIFY_FAILED: Hostname mismatch(handshake.cc:393))
SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46)
_SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142:25)
 _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1040:19)

**Comment by rohit-chouhan** [comment]
Problem is fixed, if you using you own SMTP make sure you have valid SSL in your host.

**Comment by Nwogu234** [comment]
Hi i cant verify otp
i am nor using my own stmp
